#*.* @rsyslog.lan:514
#*.* @graylog.lan:514;RSYSLOG_SyslogProtocol23Format
#*.* @loki.lan:514;RSYSLOG_SyslogProtocol23Format
*.notice;auth,authpriv.info action(type="omfwd" target="loki.lan" port="514" protocol="udp" template="RSYSLOG_SyslogProtocol23Format")