#!/bin/bash

# Настройка цветов
color() {
    tcDkG="\033[01;30m"
    tcLtBL="\033[01;34m"
    YW="\033[33m"
    GN="\033[1;92m"
    BL="\033[36m"
    CL="\033[m"
    tcRESET="\033[0m"
    TAB="  "
    
    # Иконки
    INFO="${TAB}💡${TAB}${CL}"
    DEFAULT="${TAB}⚙️${TAB}${CL}"
    HOSTNAME_ICON="${TAB}🏠${TAB}${CL}"
}

# Сбор системных данных
VIRT=$(systemd-detect-virt)
uptime_seconds=$(cat /proc/uptime | cut -f1 -d.)
upDays=$((uptime_seconds/60/60/24))
upHours=$((uptime_seconds/60/60%24))
upMins=$((uptime_seconds/60%60))

MEMORY_USED=$(free | grep Mem | awk '{printf "%.1f", $3/$2 * 100.0}')
SWAP_USED=$(free | grep Swap | awk '{if ($2>0) printf "%.1f", $3/$2 * 100.0; else print "0"}')
IP=$(hostname -I | awk '{print $1}')

if [ -f "/etc/os-release" ]; then
    OS_NAME=$(grep ^NAME /etc/os-release | cut -d= -f2 | tr -d '"')
    OS_VERSION=$(grep ^VERSION_ID /etc/os-release | cut -d= -f2 | tr -d '"')
fi

color;

# Выбор логотипа в зависимости от среды
if [ "$VIRT" = "lxc" ]; then
    raw_logo=$(cat << 'EOF'
  .____     ____  ____________  
  |    |    \   \/  /\_   ___ \ 
  |    |     \      / /    \  \/ 
  |    |___  /     \ \      \____
  |_______ \/___/\  \ \______  /
 Container\/      \_/ aWasik \/ 
EOF
)
elif [ "$VIRT" = "kvm" ]; then
    raw_logo=$(cat << 'EOF'
____   ____________    _________
\   \ /   /\______ \  /   _____/
 \   Y   /  |    |  \ \_____  \ 
  \     /   |    `   \/        \
   \___/   /_______  /_______  /
                   \/ aWasik \/ 
EOF
)
else
    raw_logo=$(cat << 'EOF'
______________    _______________
\______   \   \ /   /\_   _____/
 |     ___/\   Y   /  |    __)_ 
 |    |     \     /   |        \
 |____|      \___/   /_______  /
                      aWasik \/ 
EOF
)
fi

# Находим длину самой длинной строки в логотипе
max_len=0
while IFS= read -r line; do
    [ ${#line} -gt $max_len ] && max_len=${#line}
done <<< "$raw_logo"

# Читаем строки и дополняем их пробелами до max_len
i=1
while IFS= read -r line || [ -n "$line" ]; do
    # printf %-${max_len}s гарантирует одинаковую ширину
    declare "l$i"="$(printf "%-${max_len}s" "$line")"
    i=$((i+1))
done <<< "$raw_logo"

# Вывод приветствия
echo -e "${tcDkG}${l1}${TAB}${HOSTNAME_ICON}${YW} Hostname: ${TAB}${TAB}${TAB}$(hostname -f)${CL}"
echo -e "${tcDkG}${l2}${TAB}${INFO}${GN} IP Address: ${TAB}${TAB}${IP}${CL}"
echo -e "${tcDkG}${l3}${TAB}${DEFAULT}${BL} ${OS_NAME}: ${TAB}${TAB}${OS_VERSION}${CL}"
echo -e "${tcDkG}${l4}${TAB}${DEFAULT}${BL} Memory used: ${TAB}${TAB}${MEMORY_USED} %${CL}"
echo -e "${tcDkG}${l5}${TAB}${DEFAULT}${BL} Swap used: ${TAB}${TAB}${TAB}${SWAP_USED} %${CL}"
echo -e "${tcDkG}${l6}${TAB}${DEFAULT}${BL} System uptime: ${TAB}${upDays}d ${upHours}h ${upMins}m${CL}"
echo -e "${tcRESET}"
