#!/bin/sh

# This function sets color variables for formatting output in the terminal
color() {
    # Text Color Variables http://misc.flogisoft.com/bash/tip_colors_and_formatting
    tcLtG="\033[00;37m"    # LIGHT GRAY
    tcDkG="\033[01;30m"    # DARK GRAY
    tcLtR="\033[01;31m"    # LIGHT RED
    tcLtGRN="\033[01;32m"  # LIGHT GREEN
    tcLtBL="\033[01;34m"   # LIGHT BLUE
    tcLtP="\033[01;35m"    # LIGHT PURPLE
    tcLtC="\033[01;36m"    # LIGHT CYAN
    tcW="\033[01;37m"      # WHITE
    tcRESET="\033[0m"
    tcORANGE="\033[38;5;209m"
  # Colors
  YW=$(echo "\033[33m")
  YWB=$(echo "\033[93m")
  BL=$(echo "\033[36m")
  RD=$(echo "\033[01;31m")
  GN=$(echo "\033[1;92m")

  # Formatting
  CL=$(echo "\033[m")
  BFR="\\r\\033[K"
  BOLD=$(echo "\033[1m")
  HOLD=" "
  TAB="  "

  # System
  RETRY_NUM=10
  RETRY_EVERY=3

  # Icons
  CM="${TAB}✔️${TAB}${CL}"
  CROSS="${TAB}✖️${TAB}${CL}"
  INFO="${TAB}💡${TAB}${CL}"
  NETWORK="${TAB}📡${TAB}${CL}"
  OS="${TAB}🖥️${TAB}${CL}"
  OSVERSION="${TAB}🌟${TAB}${CL}"
  HOSTNAME="${TAB}🏠${TAB}${CL}"
  GATEWAY="${TAB}🌐${TAB}${CL}"
  DEFAULT="${TAB}⚙️${TAB}${CL}"
}

#
# Time of day
HOUR=$(date +"%H")
if [ $HOUR -lt 12  -a $HOUR -ge 0 ]; then TIME="morning"
elif [ $HOUR -lt 17 -a $HOUR -ge 12 ]; then TIME="afternoon"
else TIME="evening"
fi
#
# System uptime
uptime=`cat /proc/uptime | cut -f1 -d.`
upDays=$((uptime/60/60/24))
upHours=$((uptime/60/60%24))
upMins=$((uptime/60%60))
#
# System + Memory
SYS_LOADS=`cat /proc/loadavg | awk '{print $1}'`
MEMORY_USED=`free -b | grep Mem | awk '{print $3/$2 * 100.0}'`
SWAP_USED=`free -b | grep Swap | awk '{print $3/$2 * 100.0}'`
NUM_PROCS=`ps aux | wc -l`
IP=$(hostname -I | awk '{print $1}')  # Private IP

# Get OS information (Debian / Ubuntu)
if [ -f "/etc/os-release" ]; then
    OS_NAME=$(grep ^NAME /etc/os-release | cut -d= -f2 | tr -d '"')
    OS_VERSION=$(grep ^VERSION_ID /etc/os-release | cut -d= -f2 | tr -d '"')
elif [ -f "/etc/debian_version" ]; then
    OS_NAME="Debian"
    OS_VERSION=$(cat /etc/debian_version)
fi

color;
echo $tcDkG " .____     ____  ____________  ${TAB}${HOSTNAME}${YW} Hostname:${TAB}${TAB}${TAB}${TAB}${TAB}${GN}$(hostname -f)${CL}"
echo $tcDkG " |    |    \   \/  /\_   ___ \ ${TAB}${INFO}${YW} IP Address:${TAB}${TAB}${BOLD}${TAB}${TAB}${GN}${IP}${CL}"
echo $tcDkG " |    |     \     / /    \  \/ ${TAB}${DEFAULT}${BL} ${OS_NAME}:${TAB}${GN}${OS_VERSION}${CL}"
echo $tcDkG " |    |___  /     \ \     \____${TAB}${DEFAULT}${BL} Memory used:${TAB}${TAB}${TAB}${GN}$MEMORY_USED %${CL}"
echo $tcDkG " |_______ \/___/\  \ \______  /${TAB}${DEFAULT}${BL} Swap used:${TAB}${TAB}${TAB}${TAB}${GN}$SWAP_USED %${CL}"
echo $tcDkG "Container\/      \_/  wasik \/ ${TAB}${DEFAULT}${BL} System uptime:${TAB}${TAB}${GN}$upDays days $upHours hours $upMins minutes${CL}"
echo $tcRESET ""
